# Generated by Django 5.0.4 on 2024-04-26 03:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancer',
            name='graphs',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
