# Generated by Django 5.0.4 on 2024-04-26 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0002_cancer_graphs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancer',
            name='graphs',
        ),
    ]
